## Shareable links (yes|true|no|false)
# SHAREABLE LINKS BROKEN IN INSIDE CONTAINER, probably a permission setting or so, requires investigation.
enable_shareable_links: no 
# How many links to retain at any given time (int)
# note that each file created has a limit of 500kb
# so a link_history_size of 100 will max out at 50MB
link_history_size: 5
