# SHAREABLE LINKS BROKEN INSIDE CONTAINER, probably a permission setting or so, requires investigation.

# --------------------- Shareable links ---------------------
# Shareable links (yes|true|no|false)
enable_shareable_links: false 
# How many links to retain at any given time (int)
link_history_size: 500
# set individual file size limit in kilobytes, prevent overload
link_history_file_size: 10